module.exports = {
    "head": 'DOWNLOAD TIKTOK VIDEO WITHOUT WATERMARK',
    "place_holder": 'Paste link here ...',
    "error_1": 'Uh-oh... Something suspicious!',
    "error_2": 'It seems that your token is invalid. Are you trying to did something here?',
    "link_like": 'Please, make sure your link looks like this:',
    "f_1": 'Unlimited downloads',
    "f_1_desc": 'Download as many videos as you need, no limits or any other restrictions.',
    "f_2": 'No Watermark!',
    "f_2_desc": 'Download TT videos without a watermark, get any video without a TT logo.',
    "f_3": 'MP4 and MP3 supported',
    "f_3_desc": 'Save videos in HD, .mp4 file format, or convert it to audio .mp3.',
    "content_1": 'Download Tik Tok video without watermark',
    'content_1_desc': 'KNR Tech is a free tool helping you download videos from TikTok without a watermark online. sssTikTok is one of the most popular online TikTok video download services that can help you save videos from TikTok with the highest quality in an MP4 file format with HD resolution. To find out how to use the TikTok downloader, follow the instructions below. It is easy. You can save videos in three simple steps.',
    "content_2": 'How to download TikTok video without watermark?',
    "howto_1_title": 'Find a video',
    "howto_1_desc": 'play a video that you want to download to your mobile device, use the TikTok app;',
    "howto_2_title": 'Copy a video link',
    "howto_2_desc": 'tap "Share" (the arrow button on top of a chosen video), and then tap "Copy link";',
    "howto_3_title": 'Download',
    "howto_3_desc": 'go back to sssTikTok and paste the link in the text field on the page and tap "Download".',
    "bg_feature1_title":'Download any TikTok video on mobile phone (Android, iOS)',
    "bg_feature_desc": 'If you want to save a video on a mobile phone (Android or iOS), you need to launch the TikTok app and find a video you want to download. When you are on the video page, you will see the "Share" button on the right side of the screen, it looks like an arrow. Tap on it, and select "Copy link". After that, open Softy-pinko webpage and paste the link into the text field on the top of the page. Then hit the "Download" button to get downloadable links. The last step is to click "Download without Watermark".',
    "bg_feature2_title": 'Download TikTok video without watermark on PC',
    "bg_feature2_desc": 'This method is universal and convenient because a video will be saved without watermark in original quality. It works perfectly on Windows, Mac OS, and Linux. PC users are not required to install any additional apps, and this is another plus of this method. In order to use the TikTok video downloader on PC, Mac, or laptop you will need to copy a video link, from the Tik Tok website. Next, go back to softy-pink and paste the link in the text field on the main page. After that, you need to click on the "Download" button to get the links.',
    "copy": 'COPYRIGHT',
    "download": 'Download'
}