module.exports = {
    "head": 'DESCARGAR VIDEO TIKTOK SIN MARCA DE AGUA',
    "place_holder": 'Pegar enlace aquí ...',
    "error_1": 'Uh-oh ... ¡Algo sospechoso!',
    "error_2": 'Parece que tu token no es válido. ¿Estás intentando hacer algo aquí?',
    "link_like": 'Por favor, asegúrese de que su enlace se vea así:',
    "f_1": 'Descargas ilimitadas',
    "f_1_desc": 'Descarga todos los videos que necesites, sin límites ni otras restricciones.',
    "f_2": '¡Sin marca de agua!',
    "f_2_desc": 'Descargue videos TT sin marca de agua, obtenga cualquier video sin un logotipo TT.',
    "f_3": 'Compatible con MP4 y MP3',
    "f_3_desc": 'Guarde videos en formato de archivo HD, .mp4, o conviértalo a audio .mp3.',
    "content_1": 'Descargar video de Tik Tok sin marca de agua',
    'content_1_desc': 'KNR Tech es una herramienta gratuita que te ayuda a descargar videos de TikTok sin una marca de agua en línea. sssTikTok es uno de los servicios de descarga de videos de TikTok en línea más populares que puede ayudarlo a guardar videos de TikTok con la más alta calidad en un formato de archivo MP4 con resolución HD. Para saber cómo usar el descargador de TikTok, siga las instrucciones a continuación. Es fácil. Puede guardar videos en tres sencillos pasos.',
    "content_2": '¿Cómo descargar videos de TikTok sin marca de agua?',
    "howto_1_title": 'Encuentre un video',
    "howto_1_desc": ' reproduzca un video que desee descargar en su dispositivo móvil, use la aplicación TikTok;',
    "howto_2_title": 'Copie un enlace de video',
    "howto_2_desc": 'toque "Compartir" (el botón de flecha en la parte superior de un video elegido), y luego toque "Copiar enlace";',
    "howto_3_title": 'Descargar',
    "howto_3_desc": 'vuelva a sssTikTok y pegue el enlace en el campo de texto de la página y toque "Descargar".',
    "bg_feature1_title":'Descargue cualquier video de TikTok en un teléfono móvil (Android, iOS)',
    "bg_feature_desc": 'Si desea guardar un video en un teléfono móvil (Android o iOS), debe iniciar la aplicación TikTok y encontrar el video que desea descargar. Cuando esté en la página del video, verá el botón "Compartir" en el lado derecho de la pantalla, parece una flecha. Tócalo y selecciona "Copiar enlace". Después de eso, abra la página web de Softy-pinko y pegue el enlace en el campo de texto en la parte superior de la página. Luego presione el botón "Descargar" para obtener enlaces descargables. El último paso es hacer clic en "Descargar sin marca de agua".',
    "bg_feature2_title": 'Descargar video de TikTok sin marca de agua en PC',
    "bg_feature2_desc": 'Este método es universal y conveniente porque un video se guardará sin marca de agua en calidad original. Funciona perfectamente en Windows, Mac OS y Linux. Los usuarios de PC no están obligados a instalar ninguna aplicación adicional, y esta es otra ventaja de este método. Para usar el descargador de videos de TikTok en PC, Mac o computadora portátil, deberá copiar un enlace de video desde el sitio web de Tik Tok. A continuación, vuelva a rosa suave y pegue el enlace en el campo de texto de la página principal. Después de eso, debe hacer clic en el botón "Descargar" para obtener los enlaces.',
    "copy": 'DERECHOS DE AUTOR',
    "download": 'Descarger'
}